name: Release
permissions:
  packages: write
  contents: write
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shell-Script
        id: script
        run: |
          BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          BUILD_DATE_NUMERIC="${BUILD_DATE//[^[:digit:]]/}"
          COMMIT_HASH=${GITHUB_SHA::8}
          GITHUB_REPO=${GITHUB_REPOSITORY,,}
          PHP_VERSION="8.2"
          
          # Set output parameters to github action.
          echo ::set-output name=build_date::${BUILD_DATE}
          echo ::set-output name=build_date_numeric::${BUILD_DATE_NUMERIC}
          echo ::set-output name=commit_hash::${COMMIT_HASH}
          echo ::set-output name=github_repo::${GITHUB_REPO}
          echo ::set-output name=php_version::${PHP_VERSION}

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build-slim
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            ghcr.io/${{steps.script.outputs.github_repo}}:${{steps.script.outputs.php_version}}-${{steps.script.outputs.build_date_numeric}}.${{steps.script.outputs.commit_hash}}
      - name: Run docker
        run: |
          docker run --rm --platform linux/arm64 ghcr.io/${{steps.script.outputs.github_repo}}:${{steps.script.outputs.php_version}}-${{steps.script.outputs.build_date_numeric}}.${{steps.script.outputs.commit_hash}} php -m
